version: '3.4'

services:
  ptrampert.aspnetcore.identity.mongodb.test:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    environment:
      - MONGO_CONNECTION=mongodb://mongodb/
    volumes:
      - .:/project
    working_dir: /project
    networks:
      - test
    depends_on:
      - "mongodb"
    entrypoint: dotnet test PTrampert.AspNetCore.Identity.MongoDB.Test/PTrampert.AspNetCore.Identity.MongoDB.Test.csproj -l trx -c Release

  mongodb:
    image: mongo:4
    networks:
      - test

networks:
  test: